export const TMDB_ENDPOINTS = {
  TRENDING: "/trending/all/day",
  POPULAR_MOVIES: "/movie/popular",
  POPULAR_TV: "/tv/popular",
  SEARCH: "/search/multi",
  MOVIE_DETAILS: (id: string | number) => `/movie/${id}`,
  TV_DETAILS: (id: string | number) => `/tv/${id}`,
  GENRES_MOVIE: "/genre/movie/list",
  GENRES_TV: "/genre/tv/list",
  UPCOMING: "/movie/upcoming",
  NOW_PLAYING: "/movie/now_playing",
  TOP_RATED_MOVIES: "/movie/top_rated",
  TOP_RATED_TV: "/tv/top_rated",
  MOVIE_CREDITS: (id: string | number) => `/movie/${id}/credits`,
  TV_CREDITS: (id: string | number) => `/tv/${id}/credits`,
  MOVIE_VIDEOS: (id: string | number) => `/movie/${id}/videos`,
  TV_VIDEOS: (id: string | number) => `/tv/${id}/videos`,
  MOVIE_RECOMMENDATIONS: (id: string | number) => `/movie/${id}/recommendations`,
  TV_RECOMMENDATIONS: (id: string | number) => `/tv/${id}/recommendations`,
  MOVIE_IMAGES: (id: string | number) => `/movie/${id}/images`,
  TV_IMAGES: (id: string | number) => `/tv/${id}/images`,
  TV_SEASON_DETAILS: (id: string | number, season: number) => `/tv/${id}/season/${season}`,
} as const
